// Code generated by go run ./tools/webtypes; DO NOT EDIT.

export type APIFormat = string;
export type AttemptErrorLevel = 'key' | 'channel' | 'client';
export type AttemptStatus = 'success' | 'failed' | 'client_canceled' | 'circuit_break' | 'skipped' | 'redirect';
export type AutoGroupType = number;
export type ChannelPolicyProfile = 'standard' | 'official' | 'trusted_proxy' | 'untrusted_proxy';
export type DBImportConflictPolicy = 'reject' | 'skip' | 'replace' | 'merge';
export type GroupMode = number;
export type SettingKey = string;

export interface APIKey {
  id: number;
  uuid?: string;
  name: string;
  api_key: string;
  enabled: boolean;
  expire_at?: number;
  max_cost?: number;
  supported_models?: string;
}

export interface BaseUrl {
  url: string;
  delay: number;
}

export interface Channel {
  id: number;
  uuid?: string;
  name: string;
  type: APIFormat;
  enabled: boolean;
  base_urls: BaseUrl[];
  keys: ChannelKey[];
  model: string;
  custom_model: string;
  proxy: boolean;
  auto_sync: boolean;
  auto_group: AutoGroupType;
  custom_header: CustomHeader[];
  header_rules: HeaderRule[];
  json_rewrite_rules: JSONRewriteRule[];
  param_override?: string | null;
  raw_passthrough: boolean;
  rpm_limit: number;
  max_concurrency: number;
  channel_proxy?: string | null;
  stats?: StatsChannel | null;
  match_regex?: string | null;
  user_agent: string;
  policy_profile: ChannelPolicyProfile;
  self_healing_enabled: boolean;
  first_token_timeout_exception_enabled: boolean;
  first_token_timeout_exception_seconds: number;
  config_version: number;
}

export interface ChannelAttempt {
  channel_id: number;
  channel_key_id?: number;
  channel_key_remark?: string;
  base_url?: string;
  channel_name: string;
  model_name: string;
  attempt_num: number;
  status: AttemptStatus;
  duration: number;
  sticky?: boolean;
  health_penalty: boolean;
  action?: string;
  selection_reason?: string;
  msg?: string;
  error_level?: AttemptErrorLevel;
  error_reason?: string;
  first_token_time?: number;
}

export interface ChannelCircuitStatus {
  channel_id: number;
  channel_key_id: number;
  model_name: string;
  state: string;
  consecutive_failures: number;
  trip_count: number;
  remaining_cooldown_seconds: number;
}

export interface ChannelKey {
  id: number;
  uuid?: string;
  channel_id: number;
  enabled: boolean;
  channel_key: string;
  status_code: number;
  last_use_time_stamp: number;
  retry_after_until: number;
  total_cost: number;
  remark: string;
}

export interface ChannelKeyAddRequest {
  enabled: boolean;
  channel_key: string;
  remark: string;
}

export interface ChannelKeyUpdateRequest {
  id: number;
  enabled?: boolean | null;
  channel_key?: string | null;
  remark?: string | null;
}

export interface ChannelUpdateRequest {
  id: number;
  name?: string | null;
  type?: APIFormat | null;
  enabled?: boolean | null;
  base_urls?: BaseUrl[] | null;
  model?: string | null;
  custom_model?: string | null;
  proxy?: boolean | null;
  auto_sync?: boolean | null;
  auto_group?: AutoGroupType | null;
  custom_header?: CustomHeader[] | null;
  header_rules?: HeaderRule[] | null;
  json_rewrite_rules?: JSONRewriteRule[] | null;
  channel_proxy?: string | null;
  param_override?: string | null;
  raw_passthrough?: boolean | null;
  rpm_limit?: number | null;
  max_concurrency?: number | null;
  match_regex?: string | null;
  user_agent?: string | null;
  policy_profile?: ChannelPolicyProfile | null;
  self_healing_enabled?: boolean | null;
  first_token_timeout_exception_enabled?: boolean | null;
  first_token_timeout_exception_seconds?: number | null;
  keys_to_add?: ChannelKeyAddRequest[];
  keys_to_update?: ChannelKeyUpdateRequest[];
  keys_to_delete?: number[];
}

export interface CustomHeader {
  header_key: string;
  header_value: string;
}

export interface DBImportIssue {
  table: string;
  uuid?: string;
  field?: string;
  problem: string;
}

export interface DBImportOptions {
  dry_run: boolean;
  conflict_policy: DBImportConflictPolicy;
}

export interface HeaderRule {
  action: string;
  header_key: string;
  header_value?: string;
}

export interface JSONRewriteRule {
  action: string;
  path: string;
  value?: string | null;
}

export interface DBImportResult {
  mode: string;
  dry_run: boolean;
  conflict_policy?: DBImportConflictPolicy;
  tables?: Record<string, DBImportTableSummary>;
  issues?: DBImportIssue[];
  issues_truncated?: boolean;
  rows_affected: Record<string, number>;
  cache_refreshed: boolean;
}

export interface DBImportTableSummary {
  create: number;
  update: number;
  skip: number;
  delete: number;
  conflict: number;
  unresolved: number;
}

export interface Group {
  id: number;
  uuid?: string;
  name: string;
  enabled: boolean;
  mode: GroupMode;
  match_regex: string;
  first_token_time_out: number;
  session_keep_time: number;
  items?: GroupItem[];
}

export interface GroupItem {
  id: number;
  uuid?: string;
  group_id: number;
  type: string;
  channel_id: number;
  target_group_id: number;
  model_name: string;
  priority: number;
  weight: number;
  disabled: boolean;
}

export interface GroupItemAddRequest {
  type?: string;
  channel_id?: number;
  target_group_id?: number;
  model_name?: string;
  priority?: number;
  weight?: number;
}

export interface GroupItemUpdateRequest {
  id: number;
  priority?: number | null;
  weight?: number | null;
  disabled?: boolean | null;
}

export interface GroupUpdateRequest {
  id: number;
  name?: string | null;
  enabled?: boolean | null;
  mode?: GroupMode | null;
  match_regex?: string | null;
  first_token_time_out?: number | null;
  session_keep_time?: number | null;
  items_to_add?: GroupItemAddRequest[];
  items_to_update?: GroupItemUpdateRequest[];
  items_to_delete?: number[];
}

export interface LLMChannel {
  name: string;
  enabled: boolean;
  channel_id: number;
  channel_name: string;
}

export interface LLMInfo extends LLMPrice {
  name: string;
}

export interface LLMPrice {
  input: number;
  output: number;
  cache_read: number;
  cache_write: number;
}

export interface RelayLog {
  id: number;
  time: number;
  request_model_name: string;
  request_api_key_name: string;
  channel: number;
  channel_name: string;
  actual_model_name: string;
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  ftut: number;
  use_time: number;
  cost: number;
  request_content: string;
  response_content: string;
  error: string;
  attempts: ChannelAttempt[];
  total_attempts: number;
}

export interface Setting {
  key: SettingKey;
  value: string;
}

export interface StatsAPIKey extends StatsMetrics {
  api_key_id: number;
}

export interface StatsChannel extends StatsMetrics {
  channel_id: number;
}

export interface StatsDaily extends StatsMetrics {
  date: string;
}

export interface StatsErrorLevelCounts {
  key: number;
  channel: number;
  client: number;
}

export interface StatsErrorLevels {
  from: number;
  to: number;
  window_hours: number;
  channel_id?: number;
  scanned_logs: number;
  capacity: number;
  truncated: boolean;
  counts: StatsErrorLevelCounts;
  trend: StatsErrorLevelTrendPoint[];
}

export interface StatsErrorLevelTrendPoint extends StatsErrorLevelCounts {
  bucket_start: number;
}

export interface StatsHourly extends StatsMetrics {
  hour: number;
  date: string;
}

export interface StatsMetrics {
  input_token: number;
  output_token: number;
  reasoning_token: number;
  input_cost: number;
  output_cost: number;
  wait_time: number;
  request_success: number;
  request_failed: number;
}

export interface StatsTotal extends StatsMetrics {
  ID: number;
}

export interface UserChangePassword {
  old_password: string;
  new_password: string;
}

export interface UserChangeUsername {
  new_username: string;
  current_password: string;
}

export interface UserLogin {
  username: string;
  password: string;
  expires_in_minutes?: number | null;
  expire?: number | null;
  auth_mode?: string;
}

export interface UserLoginResponse {
  token?: string;
  expire_at?: string;
  must_change_password: boolean;
  auth_mode: string;
  webauthn_required?: boolean;
  webauthn_transaction?: string;
  webauthn_options?: unknown;
}

export interface UserStatusResponse {
  username: string;
  must_change_password: boolean;
  webauthn_enabled: boolean;
  webauthn_credentials: number;
}
