// Code generated by go run ./tools/webtypes; DO NOT EDIT.

export type APIFormat = string;
export type AttemptStatus = 'success' | 'failed' | 'circuit_break' | 'skipped' | 'redirect';
export type AutoGroupType = number;
export type GroupMode = number;
export type SettingKey = string;

export interface APIKey {
  id: number;
  name: string;
  api_key: string;
  enabled: boolean;
  expire_at?: number;
  max_cost?: number;
  supported_models?: string;
}

export interface BaseUrl {
  url: string;
  delay: number;
}

export interface Channel {
  id: number;
  name: string;
  type: APIFormat;
  enabled: boolean;
  base_urls: BaseUrl[];
  keys: ChannelKey[];
  model: string;
  custom_model: string;
  proxy: boolean;
  auto_sync: boolean;
  auto_group: AutoGroupType;
  custom_header: CustomHeader[];
  param_override?: string | null;
  raw_passthrough: boolean;
  rpm_limit: number;
  max_concurrency: number;
  channel_proxy?: string | null;
  stats?: StatsChannel | null;
  match_regex?: string | null;
}

export interface ChannelAttempt {
  channel_id: number;
  channel_key_id?: number;
  channel_key_remark?: string;
  channel_name: string;
  model_name: string;
  attempt_num: number;
  status: AttemptStatus;
  duration: number;
  sticky?: boolean;
  msg?: string;
  first_token_time?: number;
}

export interface ChannelKey {
  id: number;
  channel_id: number;
  enabled: boolean;
  channel_key: string;
  status_code: number;
  last_use_time_stamp: number;
  total_cost: number;
  remark: string;
}

export interface ChannelKeyAddRequest {
  enabled: boolean;
  channel_key: string;
  remark: string;
}

export interface ChannelKeyUpdateRequest {
  id: number;
  enabled?: boolean | null;
  channel_key?: string | null;
  remark?: string | null;
}

export interface ChannelUpdateRequest {
  id: number;
  name?: string | null;
  type?: APIFormat | null;
  enabled?: boolean | null;
  base_urls?: BaseUrl[] | null;
  model?: string | null;
  custom_model?: string | null;
  proxy?: boolean | null;
  auto_sync?: boolean | null;
  auto_group?: AutoGroupType | null;
  custom_header?: CustomHeader[] | null;
  channel_proxy?: string | null;
  param_override?: string | null;
  raw_passthrough?: boolean | null;
  rpm_limit?: number | null;
  max_concurrency?: number | null;
  match_regex?: string | null;
  keys_to_add?: ChannelKeyAddRequest[];
  keys_to_update?: ChannelKeyUpdateRequest[];
  keys_to_delete?: number[];
}

export interface CustomHeader {
  header_key: string;
  header_value: string;
}

export interface DBImportResult {
  rows_affected: Record<string, number>;
}

export interface Group {
  id: number;
  name: string;
  enabled: boolean;
  mode: GroupMode;
  match_regex: string;
  first_token_time_out: number;
  session_keep_time: number;
  items?: GroupItem[];
}

export interface GroupItem {
  id: number;
  group_id: number;
  type: string;
  channel_id: number;
  target_group_id: number;
  model_name: string;
  priority: number;
  weight: number;
  disabled: boolean;
}

export interface GroupItemAddRequest {
  type?: string;
  channel_id?: number;
  target_group_id?: number;
  model_name?: string;
  priority?: number;
  weight?: number;
}

export interface GroupItemUpdateRequest {
  id: number;
  priority?: number;
  weight?: number;
  disabled?: boolean | null;
}

export interface GroupUpdateRequest {
  id: number;
  name?: string | null;
  enabled?: boolean | null;
  mode?: GroupMode | null;
  match_regex?: string | null;
  first_token_time_out?: number | null;
  session_keep_time?: number | null;
  items_to_add?: GroupItemAddRequest[];
  items_to_update?: GroupItemUpdateRequest[];
  items_to_delete?: number[];
}

export interface LLMChannel {
  name: string;
  enabled: boolean;
  channel_id: number;
  channel_name: string;
}

export interface LLMInfo extends LLMPrice {
  name: string;
}

export interface LLMPrice {
  input: number;
  output: number;
  cache_read: number;
  cache_write: number;
}

export interface RelayLog {
  id: number;
  time: number;
  request_model_name: string;
  request_api_key_name: string;
  channel: number;
  channel_name: string;
  actual_model_name: string;
  input_tokens: number;
  output_tokens: number;
  ftut: number;
  use_time: number;
  cost: number;
  request_content: string;
  response_content: string;
  error: string;
  attempts: ChannelAttempt[];
  total_attempts: number;
}

export interface Setting {
  key: SettingKey;
  value: string;
}

export interface StatsAPIKey extends StatsMetrics {
  api_key_id: number;
}

export interface StatsChannel extends StatsMetrics {
  channel_id: number;
}

export interface StatsDaily extends StatsMetrics {
  date: string;
}

export interface StatsHourly extends StatsMetrics {
  hour: number;
  date: string;
}

export interface StatsMetrics {
  input_token: number;
  output_token: number;
  input_cost: number;
  output_cost: number;
  wait_time: number;
  request_success: number;
  request_failed: number;
}

export interface StatsModel extends StatsMetrics {
  id: number;
  name: string;
  channel_id: number;
}

export interface StatsTotal extends StatsMetrics {
  ID: number;
}

export interface UserChangePassword {
  old_password: string;
  new_password: string;
}

export interface UserChangeUsername {
  new_username: string;
}

export interface UserLogin {
  username: string;
  password: string;
  expire: number;
}

export interface UserLoginResponse {
  token: string;
  expire_at: string;
}

