package main

//go:generate go run .

import (
	"bytes"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/bestruirui/octopus/internal/model"
	"github.com/bestruirui/octopus/internal/update"
	"github.com/looplj/axonhub/llm"
)

type typeSpec struct {
	Name string
	Type reflect.Type
}

var modelTypes = []typeSpec{
	{Name: "APIKey", Type: reflect.TypeOf(model.APIKey{})},
	{Name: "BaseUrl", Type: reflect.TypeOf(model.BaseUrl{})},
	{Name: "Channel", Type: reflect.TypeOf(model.Channel{})},
	{Name: "ChannelAttempt", Type: reflect.TypeOf(model.ChannelAttempt{})},
	{Name: "ChannelKey", Type: reflect.TypeOf(model.ChannelKey{})},
	{Name: "ChannelKeyAddRequest", Type: reflect.TypeOf(model.ChannelKeyAddRequest{})},
	{Name: "ChannelKeyUpdateRequest", Type: reflect.TypeOf(model.ChannelKeyUpdateRequest{})},
	{Name: "ChannelUpdateRequest", Type: reflect.TypeOf(model.ChannelUpdateRequest{})},
	{Name: "CustomHeader", Type: reflect.TypeOf(model.CustomHeader{})},
	{Name: "DBImportResult", Type: reflect.TypeOf(model.DBImportResult{})},
	{Name: "Group", Type: reflect.TypeOf(model.Group{})},
	{Name: "GroupItem", Type: reflect.TypeOf(model.GroupItem{})},
	{Name: "GroupItemAddRequest", Type: reflect.TypeOf(model.GroupItemAddRequest{})},
	{Name: "GroupItemUpdateRequest", Type: reflect.TypeOf(model.GroupItemUpdateRequest{})},
	{Name: "GroupUpdateRequest", Type: reflect.TypeOf(model.GroupUpdateRequest{})},
	{Name: "LatestInfo", Type: reflect.TypeOf(update.LatestInfo{})},
	{Name: "LLMChannel", Type: reflect.TypeOf(model.LLMChannel{})},
	{Name: "LLMInfo", Type: reflect.TypeOf(model.LLMInfo{})},
	{Name: "LLMPrice", Type: reflect.TypeOf(model.LLMPrice{})},
	{Name: "RelayLog", Type: reflect.TypeOf(model.RelayLog{})},
	{Name: "Setting", Type: reflect.TypeOf(model.Setting{})},
	{Name: "StatsAPIKey", Type: reflect.TypeOf(model.StatsAPIKey{})},
	{Name: "StatsChannel", Type: reflect.TypeOf(model.StatsChannel{})},
	{Name: "StatsDaily", Type: reflect.TypeOf(model.StatsDaily{})},
	{Name: "StatsHourly", Type: reflect.TypeOf(model.StatsHourly{})},
	{Name: "StatsMetrics", Type: reflect.TypeOf(model.StatsMetrics{})},
	{Name: "StatsTotal", Type: reflect.TypeOf(model.StatsTotal{})},
	{Name: "UserChangePassword", Type: reflect.TypeOf(model.UserChangePassword{})},
	{Name: "UserChangeUsername", Type: reflect.TypeOf(model.UserChangeUsername{})},
	{Name: "UserLogin", Type: reflect.TypeOf(model.UserLogin{})},
	{Name: "UserLoginResponse", Type: reflect.TypeOf(model.UserLoginResponse{})},
}

var namedTypes = map[reflect.Type]string{
	reflect.TypeOf(llm.APIFormat("")):       "APIFormat",
	reflect.TypeOf(model.AttemptStatus("")): "AttemptStatus",
	reflect.TypeOf(model.AutoGroupType(0)):  "AutoGroupType",
	reflect.TypeOf(model.GroupMode(0)):      "GroupMode",
	reflect.TypeOf(model.SettingKey("")):    "SettingKey",
}

func main() {
	output, err := Generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	_, _ = os.Stdout.Write(output)
}

func Generate() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./tools/webtypes; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("export type APIFormat = string;\n")
	b.WriteString("export type AttemptStatus = 'success' | 'failed' | 'client_canceled' | 'circuit_break' | 'skipped' | 'redirect';\n")
	b.WriteString("export type AutoGroupType = number;\n")
	b.WriteString("export type GroupMode = number;\n")
	b.WriteString("export type SettingKey = string;\n")
	b.WriteString("\n")

	for _, spec := range modelTypes {
		if spec.Type.Kind() != reflect.Struct {
			return nil, fmt.Errorf("%s is not a struct", spec.Name)
		}
		writeInterface(&b, spec.Name, spec.Type)
	}
	return b.Bytes(), nil
}

func writeInterface(b *bytes.Buffer, name string, typ reflect.Type) {
	fmt.Fprintf(b, "export interface %s", name)
	if embedded := embeddedInterfaces(typ); len(embedded) > 0 {
		fmt.Fprintf(b, " extends %s", strings.Join(embedded, ", "))
	}
	b.WriteString(" {\n")
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if field.Anonymous {
			continue
		}
		jsonName, optional, ok := jsonField(field)
		if !ok {
			continue
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", jsonName, optionalMarker(field.Type, optional), tsType(field.Type))
	}
	b.WriteString("}\n\n")
}

func embeddedInterfaces(typ reflect.Type) []string {
	interfaces := make([]string, 0)
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if !field.Anonymous {
			continue
		}
		fieldType := deref(field.Type)
		if name, ok := structName(fieldType); ok {
			interfaces = append(interfaces, name)
		}
	}
	sort.Strings(interfaces)
	return interfaces
}

func jsonField(field reflect.StructField) (string, bool, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = field.Name
	}
	optional := false
	for _, part := range parts[1:] {
		if part == "omitempty" {
			optional = true
		}
	}
	return name, optional, true
}

func optionalMarker(typ reflect.Type, optional bool) string {
	if optional || typ.Kind() == reflect.Ptr {
		return "?"
	}
	return ""
}

func tsType(typ reflect.Type) string {
	if typ == reflect.TypeOf(time.Time{}) {
		return "string"
	}
	if name, ok := namedTypes[typ]; ok {
		return name
	}
	switch typ.Kind() {
	case reflect.Ptr:
		return tsType(typ.Elem()) + " | null"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		return tsType(typ.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(typ.Key()), tsType(typ.Elem()))
	case reflect.Struct:
		if name, ok := structName(typ); ok {
			return name
		}
	}
	return "unknown"
}

func structName(typ reflect.Type) (string, bool) {
	for _, spec := range modelTypes {
		if spec.Type == typ {
			return spec.Name, true
		}
	}
	return "", false
}

func deref(typ reflect.Type) reflect.Type {
	for typ.Kind() == reflect.Ptr {
		typ = typ.Elem()
	}
	return typ
}
